SELECT MA_NVIEN, COUNT(MADA) FROM PHANCONG
GROUP BY MA_NVIEN

SELECT COUNT(MADA) FROM PHANCONG WHERE MA_NVIEN = '004'

IF OBJECT_ID ('FN_deanNV') IS NOT NULL
	DROP FUNCTION FN_deanNV
GO

CREATE FUNCTION FN_deanNV (@ma_NV NVARCHAR(9))
RETURNS INT
AS
	BEGIN
		RETURN (SELECT COUNT(MADA)
		FROM PHANCONG
		WHERE MA_NVIEN = @ma_NV)
	END

PRINT ('SO DU AN NHAN VIEN DA THAM GIA: ' + CONVERT(VARCHAR,dbo.FN_deanNV('005')))