SELECT PHG, TENPHG, AVG(LUONG) FROM NHANVIEN
INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG
GROUP BY PHG, TENPHG

SELECT AVG(LUONG) FROM NHANVIEN
INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG
WHERE TENPHG = 'IT'

IF OBJECT_ID('FN_luongNV') IS NOT NULL
	DROP FUNCTION FN_luongNV
GO

CREATE FUNCTION FN_luongNV (@tenPB NVARCHAR(20))
RETURNS @luongTB_NV TABLE(FULLNAME NVARCHAR(50), LUONG FLOAT)
AS
	BEGIN
		DECLARE @luongTB FLOAT
		SELECT @luongTB = AVG(LUONG) FROM NHANVIEN
		INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG
		WHERE TENPHG = @tenPB
		INSERT INTO @luongTB_NV
			SELECT HONV + ' ' + TENLOT + ' ' + TENNV, LUONG FROM NHANVIEN
			WHERE LUONG > @luongTB
		RETURN
	END
SELECT * FROM dbo.FN_luongNV('IT')