SELECT TENPHG, TRPHG, HONV + ' ' + TENLOT + ' ' + TENNV AS 'TEN TRUONG PHONG', COUNT(MADA) AS 'SLDEAN'
FROM PHONGBAN
INNER JOIN DEAN ON DEAN.PHONG = PHONGBAN.MAPHG
INNER JOIN NHANVIEN ON NHANVIEN.MANV = PHONGBAN.TRPHG
WHERE PHONGBAN.MAPHG = '001'
GROUP BY TENPHG, TRPHG, TENNV, HONV, TENLOT

IF OBJECT_ID('FN_SLDEAN_PB') IS NOT NULL
	DROP FUNCTION FN_SLDEAN_PB
GO

CREATE FUNCTION FN_SLDEAN_PB (@maPB INT)
RETURNS @tb_dsPB TABLE(tenPB NVARCHAR(20), maTP NVARCHAR(10), tenTP NVARCHAR(50), sluong INT)
AS
	BEGIN
		INSERT INTO @tb_dsPB
		SELECT TENPHG, TRPHG, HONV + ' ' + TENLOT + ' ' + TENNV AS 'TEN TRUONG PHONG', COUNT(MADA) AS 'SLDEAN'
			FROM PHONGBAN
			INNER JOIN DEAN ON DEAN.PHONG = PHONGBAN.MAPHG
			INNER JOIN NHANVIEN ON NHANVIEN.MANV = PHONGBAN.TRPHG
			WHERE PHONGBAN.MAPHG = @maPB
			GROUP BY TENPHG, TRPHG, TENNV, HONV, TENLOT
		RETURN
	END

SELECT * FROM dbo.FN_SLDEAN_PB(4)