SELECT COUNT(*) FROM NHANVIEN WHERE PHAI LIKE 'Nam'
SELECT COUNT(*) FROM NHANVIEN WHERE PHAI LIKE N'Nữ'

CREATE FUNCTION FN_demNV_PHAI (@phai NVARCHAR(5) = N'%')
RETURNS INT
AS
	BEGIN
		RETURN (SELECT COUNT(*)
		FROM NHANVIEN
		WHERE PHAI = @phai)
	END

PRINT 'NHAN VIEN NAM: ' + CONVERT(VARCHAR,dbo.FN_demNV_PHAI('Nam'))
PRINT 'NHAN VIEN NU: ' + CONVERT(VARCHAR,dbo.FN_demNV_PHAI(N'Nữ'))