SELECT YEAR(GETDATE()) - YEAR(NGSINH) AS N'TUỔI' 
FROM NHANVIEN WHERE MANV = '001'

IF OBJECT_ID('FN_tuoiNV') IS NOT NULL
	DROP FUNCTION FN_tuoiNV
GO

CREATE FUNCTION FN_tuoiNV(@manv NVARCHAR(9))
RETURNS INT
AS
	BEGIN
		RETURN (SELECT YEAR(GETDATE()) - YEAR(NGSINH)
		FROM NHANVIEN
		WHERE MANV = @manv)
	END

PRINT 'TUOI NHAN VIEN: ' + CONVERT(NVARCHAR,dbo.FN_tuoiNV('003'))