SELECT TENPHG, TRPHG, COUNT(MANV) AS 'SOLUONGNV' FROM NHANVIEN
INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG
GROUP BY TENPHG, TRPHG

IF OBJECT_ID('VW_PBan') IS NOT NULL
	DROP FUNCTION VW_PBan
GO
CREATE VIEW VW_PBan(tenPB, hotenTP, slNV)
AS
	SELECT TOP(1) TENPHG, COUNT(nv.MaNV), CONCAT(tp.honv, ' ', tp.tenlot, ' ', tp.tennv)
	FROM NHANVIEN AS NV INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = NV.PHG
		INNER JOIN NHANVIEN AS tp ON tp.MANV=PHONGBAN.TRPHG
	GROUP BY TENPHG, tp.TENNV, tp.HONV, tp.TENLOT
	ORDER BY COUNT(NV.MaNV) DESC

SELECT * FROM VW_PBan